name: Validate Build

on:
  # Trigger when a pull request is opened or reopened
  pull_request:
    types:
      - opened
      - reopened
  # Trigger when a code review is submitted
  pull_request_review:
    types:
      - submitted
  # Allow manual runs
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Gradle
      run: gradle build
